version: '3.1'

services:

  mdoc:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/timboslicecreative/mdoc/mdoc
    container_name: mdoc
    command: npm run dev
    environment:
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - './src:/usr/src/app'
      - '/usr/src/app/node_modules'